'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PendingRecon
    
    '''<summary>
    '''upRecon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upRecon As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlBankInsti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBankInsti As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvCreditLines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCreditLines As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbltotalAmtPerCreditPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotalAmtPerCreditPeriod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlModalBankInsti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlModalBankInsti As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dtpmodalCreditDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpmodalCreditDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dtpTransDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpTransDateFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dtpTransDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpTransDateTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAmountCredited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountCredited As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnModalSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalSave As Global.System.Web.UI.WebControls.Button
End Class
