'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCMonitoring
    
    '''<summary>
    '''upMonitoring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMonitoring As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlBankInsti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBankInsti As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlReconType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReconType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlReconMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReconMonth As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlReconYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReconYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlReconStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReconStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvUC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUC As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtRowNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRowNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBankInsti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankInsti As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAmountCredited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountCredited As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCreditID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreditID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtUCARNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUCARNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtUCARAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUCARAmount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnModalSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalSave As Global.System.Web.UI.WebControls.Button
End Class
