'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UncreditedTrans
    
    '''<summary>
    '''gvUncreditedTrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUncreditedTrans As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtBankInsti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankInsti As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''dtpmodalCreditDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpmodalCreditDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTransDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTransDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransDateTo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAmountCredited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountCredited As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAmountOnFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountOnFile As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''btnModalSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalSave As Global.System.Web.UI.WebControls.Button
End Class
