'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EcollReconWCF
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/EcollReconWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IngDTResult", [Namespace]:="http://schemas.datacontract.org/2004/07/EcollReconWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Structure IngDTResult
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DTErrorMsgField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataSetResultField As System.Data.DataSet
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private isDataGetField As Boolean
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DTErrorMsg() As String
            Get
                Return Me.DTErrorMsgField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DTErrorMsgField, value) <> true) Then
                    Me.DTErrorMsgField = value
                    Me.RaisePropertyChanged("DTErrorMsg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DataSetResult() As System.Data.DataSet
            Get
                Return Me.DataSetResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataSetResultField, value) <> true) Then
                    Me.DataSetResultField = value
                    Me.RaisePropertyChanged("DataSetResult")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property isDataGet() As Boolean
            Get
                Return Me.isDataGetField
            End Get
            Set
                If (Me.isDataGetField.Equals(value) <> true) Then
                    Me.isDataGetField = value
                    Me.RaisePropertyChanged("isDataGet")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Structure
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EcollReconWCF.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As EcollReconWCF.CompositeType) As EcollReconWCF.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As EcollReconWCF.CompositeType) As System.Threading.Tasks.Task(Of EcollReconWCF.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/IngDataTable", ReplyAction:="http://tempuri.org/IService1/IngDataTableResponse")>  _
        Function IngDataTable(ByVal ProcedureName As String, ByVal IngFields() As String) As EcollReconWCF.IngDTResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/IngDataTable", ReplyAction:="http://tempuri.org/IService1/IngDataTableResponse")>  _
        Function IngDataTableAsync(ByVal ProcedureName As String, ByVal IngFields() As String) As System.Threading.Tasks.Task(Of EcollReconWCF.IngDTResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/IngDataTableCmdText", ReplyAction:="http://tempuri.org/IService1/IngDataTableCmdTextResponse")>  _
        Function IngDataTableCmdText(ByVal CommandText As String) As EcollReconWCF.IngDTResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/IngDataTableCmdText", ReplyAction:="http://tempuri.org/IService1/IngDataTableCmdTextResponse")>  _
        Function IngDataTableCmdTextAsync(ByVal CommandText As String) As System.Threading.Tasks.Task(Of EcollReconWCF.IngDTResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/IngDataTableMultiProc", ReplyAction:="http://tempuri.org/IService1/IngDataTableMultiProcResponse")>  _
        Function IngDataTableMultiProc(ByVal ProcedureName() As String) As EcollReconWCF.IngDTResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/IngDataTableMultiProc", ReplyAction:="http://tempuri.org/IService1/IngDataTableMultiProcResponse")>  _
        Function IngDataTableMultiProcAsync(ByVal ProcedureName() As String) As System.Threading.Tasks.Task(Of EcollReconWCF.IngDTResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits EcollReconWCF.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of EcollReconWCF.IService1)
        Implements EcollReconWCF.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements EcollReconWCF.IService1.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements EcollReconWCF.IService1.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As EcollReconWCF.CompositeType) As EcollReconWCF.CompositeType Implements EcollReconWCF.IService1.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As EcollReconWCF.CompositeType) As System.Threading.Tasks.Task(Of EcollReconWCF.CompositeType) Implements EcollReconWCF.IService1.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function IngDataTable(ByVal ProcedureName As String, ByVal IngFields() As String) As EcollReconWCF.IngDTResult Implements EcollReconWCF.IService1.IngDataTable
            Return MyBase.Channel.IngDataTable(ProcedureName, IngFields)
        End Function
        
        Public Function IngDataTableAsync(ByVal ProcedureName As String, ByVal IngFields() As String) As System.Threading.Tasks.Task(Of EcollReconWCF.IngDTResult) Implements EcollReconWCF.IService1.IngDataTableAsync
            Return MyBase.Channel.IngDataTableAsync(ProcedureName, IngFields)
        End Function
        
        Public Function IngDataTableCmdText(ByVal CommandText As String) As EcollReconWCF.IngDTResult Implements EcollReconWCF.IService1.IngDataTableCmdText
            Return MyBase.Channel.IngDataTableCmdText(CommandText)
        End Function
        
        Public Function IngDataTableCmdTextAsync(ByVal CommandText As String) As System.Threading.Tasks.Task(Of EcollReconWCF.IngDTResult) Implements EcollReconWCF.IService1.IngDataTableCmdTextAsync
            Return MyBase.Channel.IngDataTableCmdTextAsync(CommandText)
        End Function
        
        Public Function IngDataTableMultiProc(ByVal ProcedureName() As String) As EcollReconWCF.IngDTResult Implements EcollReconWCF.IService1.IngDataTableMultiProc
            Return MyBase.Channel.IngDataTableMultiProc(ProcedureName)
        End Function
        
        Public Function IngDataTableMultiProcAsync(ByVal ProcedureName() As String) As System.Threading.Tasks.Task(Of EcollReconWCF.IngDTResult) Implements EcollReconWCF.IService1.IngDataTableMultiProcAsync
            Return MyBase.Channel.IngDataTableMultiProcAsync(ProcedureName)
        End Function
    End Class
End Namespace
