'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace ADWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AuthenticateUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AuthenticateUserWithDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AuthenticateUserWithDetailsViaLFMOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AuthenticateUserWithDetailsViaUsernameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDisplayNameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserNameDetailsViaLoginNameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isUserNameExistingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.EcollReconFacility.My.MySettings.Default.EcollReconFacility_ADWS_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AuthenticateUserCompleted As AuthenticateUserCompletedEventHandler
        
        '''<remarks/>
        Public Event AuthenticateUserWithDetailsCompleted As AuthenticateUserWithDetailsCompletedEventHandler
        
        '''<remarks/>
        Public Event AuthenticateUserWithDetailsViaLFMCompleted As AuthenticateUserWithDetailsViaLFMCompletedEventHandler
        
        '''<remarks/>
        Public Event AuthenticateUserWithDetailsViaUsernameCompleted As AuthenticateUserWithDetailsViaUsernameCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDisplayNameCompleted As GetDisplayNameCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserNameDetailsViaLoginNameCompleted As GetUserNameDetailsViaLoginNameCompletedEventHandler
        
        '''<remarks/>
        Public Event isUserNameExistingCompleted As isUserNameExistingCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUser", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AuthenticateUser(ByVal strLoginName As String, ByVal strPassword As String) As String
            Dim results() As Object = Me.Invoke("AuthenticateUser", New Object() {strLoginName, strPassword})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserAsync(ByVal strLoginName As String, ByVal strPassword As String)
            Me.AuthenticateUserAsync(strLoginName, strPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserAsync(ByVal strLoginName As String, ByVal strPassword As String, ByVal userState As Object)
            If (Me.AuthenticateUserOperationCompleted Is Nothing) Then
                Me.AuthenticateUserOperationCompleted = AddressOf Me.OnAuthenticateUserOperationCompleted
            End If
            Me.InvokeAsync("AuthenticateUser", New Object() {strLoginName, strPassword}, Me.AuthenticateUserOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateUserOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateUserCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateUserCompleted(Me, New AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUserWithDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AuthenticateUserWithDetails(ByVal strLoginName As String, ByVal strPassword As String) As LoginResult
            Dim results() As Object = Me.Invoke("AuthenticateUserWithDetails", New Object() {strLoginName, strPassword})
            Return CType(results(0),LoginResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserWithDetailsAsync(ByVal strLoginName As String, ByVal strPassword As String)
            Me.AuthenticateUserWithDetailsAsync(strLoginName, strPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserWithDetailsAsync(ByVal strLoginName As String, ByVal strPassword As String, ByVal userState As Object)
            If (Me.AuthenticateUserWithDetailsOperationCompleted Is Nothing) Then
                Me.AuthenticateUserWithDetailsOperationCompleted = AddressOf Me.OnAuthenticateUserWithDetailsOperationCompleted
            End If
            Me.InvokeAsync("AuthenticateUserWithDetails", New Object() {strLoginName, strPassword}, Me.AuthenticateUserWithDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateUserWithDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateUserWithDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateUserWithDetailsCompleted(Me, New AuthenticateUserWithDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUserWithDetailsViaLFM", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AuthenticateUserWithDetailsViaLFM(ByVal strInputName As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> LoginResultType2()
            Dim results() As Object = Me.Invoke("AuthenticateUserWithDetailsViaLFM", New Object() {strInputName})
            Return CType(results(0),LoginResultType2())
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserWithDetailsViaLFMAsync(ByVal strInputName As String)
            Me.AuthenticateUserWithDetailsViaLFMAsync(strInputName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserWithDetailsViaLFMAsync(ByVal strInputName As String, ByVal userState As Object)
            If (Me.AuthenticateUserWithDetailsViaLFMOperationCompleted Is Nothing) Then
                Me.AuthenticateUserWithDetailsViaLFMOperationCompleted = AddressOf Me.OnAuthenticateUserWithDetailsViaLFMOperationCompleted
            End If
            Me.InvokeAsync("AuthenticateUserWithDetailsViaLFM", New Object() {strInputName}, Me.AuthenticateUserWithDetailsViaLFMOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateUserWithDetailsViaLFMOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateUserWithDetailsViaLFMCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateUserWithDetailsViaLFMCompleted(Me, New AuthenticateUserWithDetailsViaLFMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUserWithDetailsViaUsername", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AuthenticateUserWithDetailsViaUsername(ByVal strLoginName As String) As ADSearchResult
            Dim results() As Object = Me.Invoke("AuthenticateUserWithDetailsViaUsername", New Object() {strLoginName})
            Return CType(results(0),ADSearchResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserWithDetailsViaUsernameAsync(ByVal strLoginName As String)
            Me.AuthenticateUserWithDetailsViaUsernameAsync(strLoginName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserWithDetailsViaUsernameAsync(ByVal strLoginName As String, ByVal userState As Object)
            If (Me.AuthenticateUserWithDetailsViaUsernameOperationCompleted Is Nothing) Then
                Me.AuthenticateUserWithDetailsViaUsernameOperationCompleted = AddressOf Me.OnAuthenticateUserWithDetailsViaUsernameOperationCompleted
            End If
            Me.InvokeAsync("AuthenticateUserWithDetailsViaUsername", New Object() {strLoginName}, Me.AuthenticateUserWithDetailsViaUsernameOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateUserWithDetailsViaUsernameOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateUserWithDetailsViaUsernameCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateUserWithDetailsViaUsernameCompleted(Me, New AuthenticateUserWithDetailsViaUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDisplayName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDisplayName(ByVal Username As String) As String
            Dim results() As Object = Me.Invoke("GetDisplayName", New Object() {Username})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDisplayNameAsync(ByVal Username As String)
            Me.GetDisplayNameAsync(Username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDisplayNameAsync(ByVal Username As String, ByVal userState As Object)
            If (Me.GetDisplayNameOperationCompleted Is Nothing) Then
                Me.GetDisplayNameOperationCompleted = AddressOf Me.OnGetDisplayNameOperationCompleted
            End If
            Me.InvokeAsync("GetDisplayName", New Object() {Username}, Me.GetDisplayNameOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDisplayNameOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDisplayNameCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDisplayNameCompleted(Me, New GetDisplayNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserNameDetailsViaLoginName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserNameDetailsViaLoginName(ByVal LoginName As String) As UserNameDetails
            Dim results() As Object = Me.Invoke("GetUserNameDetailsViaLoginName", New Object() {LoginName})
            Return CType(results(0),UserNameDetails)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserNameDetailsViaLoginNameAsync(ByVal LoginName As String)
            Me.GetUserNameDetailsViaLoginNameAsync(LoginName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserNameDetailsViaLoginNameAsync(ByVal LoginName As String, ByVal userState As Object)
            If (Me.GetUserNameDetailsViaLoginNameOperationCompleted Is Nothing) Then
                Me.GetUserNameDetailsViaLoginNameOperationCompleted = AddressOf Me.OnGetUserNameDetailsViaLoginNameOperationCompleted
            End If
            Me.InvokeAsync("GetUserNameDetailsViaLoginName", New Object() {LoginName}, Me.GetUserNameDetailsViaLoginNameOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserNameDetailsViaLoginNameOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserNameDetailsViaLoginNameCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserNameDetailsViaLoginNameCompleted(Me, New GetUserNameDetailsViaLoginNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isUserNameExisting", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isUserNameExisting(ByVal strLoginName As String) As String
            Dim results() As Object = Me.Invoke("isUserNameExisting", New Object() {strLoginName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isUserNameExistingAsync(ByVal strLoginName As String)
            Me.isUserNameExistingAsync(strLoginName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isUserNameExistingAsync(ByVal strLoginName As String, ByVal userState As Object)
            If (Me.isUserNameExistingOperationCompleted Is Nothing) Then
                Me.isUserNameExistingOperationCompleted = AddressOf Me.OnisUserNameExistingOperationCompleted
            End If
            Me.InvokeAsync("isUserNameExisting", New Object() {strLoginName}, Me.isUserNameExistingOperationCompleted, userState)
        End Sub
        
        Private Sub OnisUserNameExistingOperationCompleted(ByVal arg As Object)
            If (Not (Me.isUserNameExistingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isUserNameExistingCompleted(Me, New isUserNameExistingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LoginResult
        
        Private isLoginValidField As Boolean
        
        Private lastNameField As String
        
        Private firstNameField As String
        
        Private middleNameField As String
        
        Private departmentField As String
        
        Private errorMessageField As String
        
        '''<remarks/>
        Public Property isLoginValid() As Boolean
            Get
                Return Me.isLoginValidField
            End Get
            Set
                Me.isLoginValidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MiddleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UserNameDetails
        
        Private isLoginNameValidField As String
        
        Private lastNameField As String
        
        Private firstNameField As String
        
        Private middleNameField As String
        
        Private errorMessageField As String
        
        '''<remarks/>
        Public Property isLoginNameValid() As String
            Get
                Return Me.isLoginNameValidField
            End Get
            Set
                Me.isLoginNameValidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MiddleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ADSearchResult
        
        Private isLoginValidField As Boolean
        
        Private lastNameField As String
        
        Private firstNameField As String
        
        Private middleNameField As String
        
        Private departmentField As String
        
        Private positionField As String
        
        Private emailField As String
        
        Private errorMessageField As String
        
        '''<remarks/>
        Public Property isLoginValid() As Boolean
            Get
                Return Me.isLoginValidField
            End Get
            Set
                Me.isLoginValidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MiddleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Position() As String
            Get
                Return Me.positionField
            End Get
            Set
                Me.positionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LoginResultType2
        
        Private usernameField As String
        
        Private lastNameField As String
        
        Private firstNameField As String
        
        Private middleNameField As String
        
        Private departmentField As String
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MiddleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub AuthenticateUserCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateUserCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub AuthenticateUserWithDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateUserWithDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateUserWithDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As LoginResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),LoginResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub AuthenticateUserWithDetailsViaLFMCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateUserWithDetailsViaLFMCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateUserWithDetailsViaLFMCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As LoginResultType2()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),LoginResultType2())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub AuthenticateUserWithDetailsViaUsernameCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateUserWithDetailsViaUsernameCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateUserWithDetailsViaUsernameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ADSearchResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ADSearchResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetDisplayNameCompletedEventHandler(ByVal sender As Object, ByVal e As GetDisplayNameCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDisplayNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetUserNameDetailsViaLoginNameCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserNameDetailsViaLoginNameCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserNameDetailsViaLoginNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As UserNameDetails
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),UserNameDetails)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub isUserNameExistingCompletedEventHandler(ByVal sender As Object, ByVal e As isUserNameExistingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isUserNameExistingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
